import Head from "next/head";
import Homepage from "../components/Homepage";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TJ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div class="container-fluid p-0 m-0 text-white text-center bg-success">
        <Homepage />
      </div>
    </div>
  );
}
