import React from 'react'
import styles from "../styles/Home.module.css";
import Head from 'next/head';
import NavSideBar from '../components/navbarComponents/NavSideBar';
import ScrollSection from '../components/homeComponents/ScrollSection';


const projects = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TJ | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid p-0 m-0">
      <div className="container-fluid m-0 p-0">
          <div className="d-flex flex-row">
            <div className="col-3 h-100">
              <NavSideBar />
            </div>
            <div className="col-9 h-100">
              <ScrollSection />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default projects